apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-demo
        version: v1
    spec:
      containers:
      - image: ryanlime/k8s-demo:1.0
        imagePullPolicy: IfNotPresent
        name: k8s-demo
        ports:
        - containerPort: 8080
